import { useEffect, useMemo, useState } from "react";
import TopBar from "../components/TopBar";
import Loading from "../components/Loading";
import Table from "../components/Table";
import { apiFetch } from "../lib/api";
import { Search } from "lucide-react";

export default function Internships() {
  const [list, setList] = useState([]);
  const [recs, setRecs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [q, setQ] = useState("");

  useEffect(() => {
    (async () => {
      try {
        const [a, b] = await Promise.all([apiFetch("/internships"), apiFetch("/internships/recommendations/me")]);
        setList(a.items || []); setRecs(b.items || []);
      } finally { setLoading(false); }
    })();
  }, []);

  const filtered = useMemo(() => {
    if (!q.trim()) return list;
    const s = q.toLowerCase();
    return list.filter((it) => `${it.company_name} ${it.role} ${it.domain} ${it.skills_required}`.toLowerCase().includes(s));
  }, [list, q]);

  const columns = [
    { key: "company_name", header: "Company" },
    { key: "role", header: "Role" },
    { key: "domain", header: "Domain", className: "w-40" },
    { key: "salary_package", header: "Package", className: "w-32" },
    { key: "skills_required", header: "Skills", className: "min-w-[260px]" },
  ];

  return (
    <div className="space-y-6">
      <TopBar
        title="Internships"
        subtitle="Recommendations = skills overlap + domain fit + leaderboard strength."
        right={
          <div className="hidden md:flex items-center gap-2">
            <div className="relative">
              <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input className="input pl-9 w-72" placeholder="Search internships..." value={q} onChange={(e) => setQ(e.target.value)} />
            </div>
          </div>
        }
      />
      <div className="md:hidden">
        <div className="relative">
          <Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input className="input pl-9" placeholder="Search internships..." value={q} onChange={(e) => setQ(e.target.value)} />
        </div>
      </div>

      {loading ? <Loading label="Loading internships..." /> : null}

      {!loading ? (
        <div className="grid lg:grid-cols-3 gap-4">
          <div className="card p-4 lg:col-span-1">
            <div className="text-sm font-extrabold">Your top recommendations</div>
            <div className="text-xs text-slate-500 mt-1">Top matches generated by backend.</div>
            <div className="mt-4 space-y-3">
              {(recs || []).slice(0, 8).map((r, idx) => (
                <div key={`${r.internship.id}-${idx}`} className="rounded-xl border border-slate-100 bg-white p-3">
                  <div className="flex items-center justify-between gap-2">
                    <div className="text-sm font-bold">{r.internship.company_name}</div>
                    <span className="badge">{r.match_score.toFixed(0)}%</span>
                  </div>
                  <div className="text-xs text-slate-600 mt-1">{r.internship.role}</div>
                  <div className="text-xs text-slate-500 mt-1">{r.internship.domain}</div>
                  <div className="text-xs text-slate-500 mt-2">{r.internship.skills_required}</div>
                </div>
              ))}
              {(recs || []).length === 0 ? (
                <div className="text-sm text-slate-600">No recommendations yet. Add skills in Persona + run resume match.</div>
              ) : null}
            </div>
          </div>

          <div className="lg:col-span-2 space-y-3">
            <div className="card p-4">
              <div className="text-sm font-extrabold">All internships</div>
              <div className="text-xs text-slate-500 mt-1">Filter and explore.</div>
            </div>
            <Table columns={columns} rows={filtered} rowKey={(r) => r.id} />
          </div>
        </div>
      ) : null}
    </div>
  );
}
